<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <PlatformTarget>x86</PlatformTarget>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <Platforms>x86;AnyCPU</Platforms>
    <AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>HPParking</RootNamespace>
    <AssemblyName>HPParking</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.13" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SimpleLPR3">
      <HintPath>Libs\x86\SimpleLPR3.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\SimpleLPR3_key.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Libs\x86\**\*.*" Exclude="Libs\x86\SimpleLPR3.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
      <Visible>false</Visible>
    </None>
    <None Include="Libs\native\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>native\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <Visible>false</Visible>
    </None>
  </ItemGroup>

</Project>