//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPParking.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPParking.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;license&gt;
        ///  &lt;e k=&quot;PRODUCT&quot; v=&quot;SimpleLPR&quot; /&gt;
        ///  &lt;e k=&quot;CITY&quot; v=&quot;SOC TRANG&quot; /&gt;
        ///  &lt;e k=&quot;COMPANY&quot; v=&quot;VINPARKING&quot; /&gt;
        ///  &lt;e k=&quot;COUNTRY&quot; v=&quot;Viet Nam&quot; /&gt;
        ///  &lt;e k=&quot;EMAIL&quot; v=&quot;luongphamthaihuy@gmail.com&quot; /&gt;
        ///  &lt;e k=&quot;ENCODING&quot; v=&quot;UTF8&quot; /&gt;
        ///  &lt;e k=&quot;FIRSTNAME&quot; v=&quot;Huy&quot; /&gt;
        ///  &lt;e k=&quot;ISO_CODE&quot; v=&quot;VN&quot; /&gt;
        ///  &lt;e k=&quot;ITEM_NAME&quot; v=&quot;SimpleLPR&quot; /&gt;
        ///  &lt;e k=&quot;LANGUAGE_ID&quot; v=&quot;1&quot; /&gt;
        ///  &lt;e k=&quot;LASTNAME&quot; v=&quot;Luong&quot; /&gt;
        ///  &lt;e k=&quot;NLALLOW&quot; v=&quot;NO&quot; /&gt;
        ///  &lt;e k=&quot;PRODUCT_ID&quot; v=&quot;300183841&quot; /&gt;
        ///  &lt;e k=&quot;PRODUCT_N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleLPR3_key {
            get {
                return ResourceManager.GetString("SimpleLPR3_key", resourceCulture);
            }
        }
    }
}
