server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Hỗ trợ React Router tránh lỗi 404 khi người dùng F5 tại các route con
        try_files $uri $uri/ /index.html;
    }
}
